baseURL = 'https://harshmishra2991.github.io/'
relativeURLs = true
languageCode = 'en-us'
title = 'Harsh Mishra'
theme = 'PaperMod'

enableRobotsTXT = true


[params]
description = "Product, investing, systems thinking"
author = "Harsh Mishra"
defaultTheme = "light"
ShowReadingTime = true
ShowShareButtons = true

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1


[[menu.main]]
name = "About"
url = "/about/"
weight = 2

